basePath: /v2
definitions:
  api.CreateDidRequestBody:
    properties:
      method:
        example: byd50
        type: string
      public_key_base58:
        example: 3VZ6oJdR8i1qKX7kH3Yv9d7w7wzgn...
        type: string
    type: object
  api.CreateDidResponse:
    properties:
      did:
        example: did:byd50:1234567890abcdef
        type: string
    type: object
  api.ErrorResponse:
    properties:
      code:
        example: INVALID_PARAM
        type: string
      message:
        example: method and public_key_base58 are required
        type: string
    type: object
  api.GetDidPublicKeyResponse:
    properties:
      publicKeyBase58:
        example: 3VZ6oJdR8i1qKX7kH3Yv9d7w7wzgn...
        type: string
    type: object
  api.GetDidResponse:
    properties:
      document:
        example: '{\"@context\":[\"https://www.w3.org/ns/did/v1\"],\"id\":\"did:byd50:123\",\"verificationMethod\":[...]}'
        type: string
    type: object
host: localhost:8080
info:
  contact:
    email: support@swagger.io
    name: API Support
    url: http://www.swagger.io/support
  description: This is a sample server for DID ServiceEndpoint.
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: http://swagger.io/terms/
  title: DID Phase 2 Test API
  version: "1.0"
paths:
  /testapi/create-did:
    post:
      consumes:
      - application/json
      description: Create a DID using method and public key.
      operationId: createDid
      parameters:
      - description: Create DID request
        in: body
        name: CreateDidRequestBody
        required: true
        schema:
          $ref: '#/definitions/api.CreateDidRequestBody'
      produces:
      - application/json
      responses:
        "200":
          description: ok" example({"did":"did:byd50:1234567890abcdef"})
          schema:
            $ref: '#/definitions/api.CreateDidResponse'
        "400":
          description: bad request" example({"code":"INVALID_PARAM","message":"method
            and public_key_base58 are required"})
          schema:
            $ref: '#/definitions/api.ErrorResponse'
        "500":
          description: internal error" example({"code":"INTERNAL_ERROR","message":"failed
            to create did"})
          schema:
            $ref: '#/definitions/api.ErrorResponse'
      security:
      - ApiKeyAuth: []
      summary: Create DID
  /testapi/get-did-public-key/{some_id}:
    get:
      consumes:
      - application/json
      description: Resolve a DID and return its public key (Base58).
      operationId: getDidPublicKey
      parameters:
      - description: DID
        in: path
        name: some_id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: ok" example({"publicKeyBase58":"3VZ6oJdR8i1qKX7kH3Yv9d7w7wzgn..."})
          schema:
            $ref: '#/definitions/api.GetDidPublicKeyResponse'
        "400":
          description: bad request" example({"code":"INVALID_PARAM","message":"did
            is required"})
          schema:
            $ref: '#/definitions/api.ErrorResponse'
        "404":
          description: not found" example({"code":"NOT_FOUND","message":"public key
            not found"})
          schema:
            $ref: '#/definitions/api.ErrorResponse'
      security:
      - ApiKeyAuth: []
      summary: Get DID Public Key
  /testapi/get-did/{some_id}:
    get:
      consumes:
      - application/json
      description: Resolve a DID and return its DID Document.
      operationId: getDidDocument
      parameters:
      - description: DID
        in: path
        name: some_id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: ok" example({"document":"{...did document json...}"})
          schema:
            $ref: '#/definitions/api.GetDidResponse'
        "400":
          description: bad request" example({"code":"INVALID_PARAM","message":"did
            is required"})
          schema:
            $ref: '#/definitions/api.ErrorResponse'
        "404":
          description: not found" example({"code":"NOT_FOUND","message":"did document
            not found"})
          schema:
            $ref: '#/definitions/api.ErrorResponse'
      security:
      - ApiKeyAuth: []
      summary: Get DID Document
securityDefinitions:
  ApiKeyAuth:
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
